### ISSUE TITLE
Identical submissions have different execution times and scores

### ISSUE THREAD

**Issue by Maritsu** [varqox/sim-project#36]
A thing I've noticed but forgot to report until now is that if a submission is on the edge of a TLE but passes all tests, the scores can be wildly different (why? no clue.).

# Example
Two submissions to the same problem with different scores: [120846](https://sim.13lo.pl/s/120846) and [120873](https://sim.13lo.pl/s/120873).
I have checked the codes and they are exactly the same code, as even their hashes match up (see screenshot below). However, their scores are different by a whopping 12 points (44 and 56, respectively).  

![image](https://github.com/user-attachments/assets/3f40559f-48c2-4f05-87e3-575862bf42dd)

**Comment by varqox** [comment]
Okay, in Polish Olympiad in Informatics (OI) you get 100% score if for all tests you are below 50% time limit (TL), after that score linearly goes down to 0 on TL. This is how it looks like on a graph:
![image](https://github.com/user-attachments/assets/1a81e98a-4dd1-4867-bd16-0bfadb5ff76a)
Sim does it slightly differently (see: https://github.com/varqox/sim-project/blob/main/subprojects/simlib/src/sim/judge_worker.cc#L392-L404 and https://github.com/varqox/sim-project/blob/2ff48a24626e51bddb22b3d08ef04539b5ab5d51/subprojects/simlib/include/simlib/sim/judge_worker.hh#L393-L408) resulting in the following plot:
![image](https://github.com/user-attachments/assets/e7bcaa1d-b80e-47d3-9830-4f52329def9b)

What is important is the runtime of the model solution let's call it $t_m$, the TL is set to something slightly above $3 t_m$, to be exact: $3 t_m + 0.3 \frac{2}{t_m^2 + 2}$. See: https://github.com/varqox/sim-project/blob/2ff48a24626e51bddb22b3d08ef04539b5ab5d51/subprojects/simlib/include/simlib/sim/conver.hh#L134-L142. This part $0.3 \frac{2}{t_m^2 + 2}$ is for "system noise" - there is a problem measuring runtime time (to be exact CPU run time is used) that many many factors make the measurement vary. This small part $0.3 \frac{2}{t_m^2 + 2}$ is to create a safe margin for user's solution in case of larger system noise.

Back to the calculating of the score. Given the above formulas, you get 100% points if you are at most 2x slower than the model solution on the same test. Between 2x to 3x the score linearly falls down to 0. Analogically as in OI. But in OI time limits are set manually and are adjusted to hardware... this is a simplification because OI counts instructions the execution of the program took instead of cpu cycles (= CPU runtime). However, the idea is the same, after half of the TL score linearly falls down to 0. During sim development, I realized that using the same approach as OI uses is problematic if we take TL = $4t_m$ and cut score from $2t_m$ - the same as in OI. This extends the judging time compared to the current approach significantly, especially for the brute-force solutions that get TLE on most of the larger tests (larger test have larger time limits = more time wasted). This is why Sim uses analogous, but different method.

One more thing, the score for a group of tests is the minimum coefficient calculated as described above times the max score of that group. So the worst test determines the score for the whole group.

The score variation comes from time variation of the two submissions. One has:
4.04 / 4.14 on one test, the other has 3.74 / 4.14 on the same test. 4.04 is very close to 4.14, that is why the score for the whole group is only 4/60; 3.74 is far less than 4.14, hence the score difference: 16/60. In fact in the second case the coefficient is calculated from a different test... But argument stays the same.

The problem of time variation of the solution is a hard problem to solve and impossible eliminate entirely. OI counts instructions, but if you experiment yourself (try perf stat path/to/solution < test.in > /dev/null), you will see that even the number of executed instructions vary significantly per run, where theoretically it should be the same.

To get more points you need to get the author of the problem / some admin to change the time limits or (a more common way) write a faster solution :)

**Comment by varqox** [comment]
In case of such problems you can always rejudge the submission.
